[platformio]
src_dir = stromzaehler

[env:mkrwifi1010]
platform  = atmelsam
board     = mkrwifi1010
framework = arduino

lib_deps =
    arduino-libraries/WiFiNINA
    knolleary/PubSubClient
    rweather/Crypto
    ; ArduinoOTA is bundled with framework-arduino-samd, no separate entry needed
