[platformio]
src_dir = stromzaehler

[env:mkrwifi1010]
platform  = atmelsam
board     = mkrwifi1010
framework = arduino

; makes ~/Arduino/libraries/ available so config.h can #include <Configuration.h>
lib_extra_dirs = ~/Arduino/libraries

lib_deps =
    arduino-libraries/WiFiNINA
    knolleary/PubSubClient
    rweather/Crypto
    ; OTA: WiFi101OTA conflicts with WiFiNINA — deferred
