[env:mkrwifi1010]
platform  = atmelsam
board     = mkrwifi1010
framework = arduino
src_dir   = stromzaehler

lib_deps =
    arduino-libraries/WiFiNINA
    knolleary/PubSubClient
    rweather/Crypto
    arduino-libraries/ArduinoOTA
